# 第6章 固有表現認識(Named Entity Recognition)

## 6.2 データセット・前処理・評価指標

#### 準備

In [1]:
!pip install 'datasets<4.0.0' 'transformers[ja,torch]<4.41.0'  spacy-alignments seqeval

Collecting datasets<4.0.0
  Downloading datasets-3.6.0-py3-none-any.whl.metadata (19 kB)
Collecting transformers<4.41.0 (from transformers[ja,torch]<4.41.0)
  Downloading transformers-4.40.2-py3-none-any.whl.metadata (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.0/138.0 kB 4.5 MB/s eta 0:00:00
Collecting spacy-alignments
  Downloading spacy_alignments-0.9.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.6 kB)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets<4.0.0) (6.0.3)
Collecting huggingface-hub>=0.24.0 (from datasets<4.0.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<4.41.0->transformers[ja,torch]<4.41.0) (2025.11.3)
Collecting tokenizers<0.20,>=0.19 (from transformers<4.41.0->transformers[ja,torch]<4.41.0)
  Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers<4.41.0->transformers[ja,torch]<4.41.0) (0.7.0)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.12/dist-packages (from seqeval) (1.6.1)
Collecting fugashi>=1.0 (from transformers[ja,torch]<4.41.0)
  Downloading fugashi-1.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (7.3 kB)
Collecting ipadic<2.0,>=1.0.0 (from transformers[ja,torch]<4.41.0)
  Downloading ipadic-1.0.0.tar.gz (13.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 85.7 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Collecting unidic-lite>=1.0.7 (from transformers[ja,torch]<4.41.0)
  Downloading unidic-lite-1.0.8.tar.gz (47.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 MB 20.1 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Collecting unidic>=1.0.2 (from transformers[ja,torch]<4.41.0)
  Downloading unidic-1.1.0.tar.gz (7.7 kB)
  Preparing metadata (setup.py) ... done
Collecting sudachipy>=0.6.6 (from transformers[ja,torch]<4.41.0)
  Downloading sudachipy-0.6.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (12 kB)
Collecting sudachidict-core>=20220729 (from transformers[ja,torch]<4.41.0)
  Downloading sudachidict_core-20260428-py3-none-any.whl.metadata (2.7 kB)
Collecting rhoknp<1.3.1,>=1.1.0 (from transformers[ja,torch]<4.41.0)
  Downloading rhoknp-1.3.0-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from transformers[ja,torch]<4.41.0) (2.10.0+cu128)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from transformers[ja,torch]<4.41.0) (1.13.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.21.0->transformers[ja,torch]<4.41.0) (5.9.5)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets<4.0.0) (1.4.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets<4.0.0) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets<4.0.0) (2026.4.22)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->transformers[ja,torch]<4.41.0) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->transformers[ja,torch]<4.41.0) (1.5.3)
Collecting wasabi<1.0.0,>=0.6.0 (from unidic>=1.0.2->transformers[ja,torch]<4.41.0)
  Downloading wasabi-0.10.1-py3-none-any.whl.metadata (28 kB)
Collecting plac<2.0.0,>=1.1.3 (from unidic>=1.0.2->transformers[ja,torch]<4.41.0)
  Downloading plac-1.4.5-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets<4.0.0) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets<4.0.0) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets<4.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->transformers[ja,torch]<4.41.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->transformers[ja,torch]<4.41.0) (3.0.3)
Downloading datasets-3.6.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 44.6 MB/s eta 0:00:00
Downloading transformers-4.40.2-py3-none-any.whl (9.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 127.6 MB/s eta 0:00:0000:0100:01
Downloading spacy_alignments-0.9.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (313 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.4/313.4 kB 27.8 MB/s eta 0:00:00
Downloading fugashi-1.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (694 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 694.9/694.9 kB 56.3 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 52.1 MB/s eta 0:00:00
Downloading rhoknp-1.3.0-py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 10.2 MB/s eta 0:00:00
Downloading sudachidict_core-20260428-py3-none-any.whl (72.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 MB 12.3 MB/s eta 0:00:00:00:0100:01
Downloading sudachipy-0.6.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 92.9 MB/s eta 0:00:00
Downloading tokenizers-0.19.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 99.4 MB/s eta 0:00:00:00:01
Downloading plac-1.4.5-py2.py3-none-any.whl (22 kB)
Downloading wasabi-0.10.1-py3-none-any.whl (26 kB)
Building wheels for collected packages: seqeval, ipadic, unidic, unidic-lite
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=402ad8c4d5e5ba062c733c9709924f5a590281d6731ff407c9888c2dd5d55c77
  Stored in directory: /root/.cache/pip/wheels/5f/b8/73/0b2c1a76b701a677653dd79ece07cfabd7457989dbfbdcd8d7
  Building wheel for ipadic (setup.py) ... done
  Created wheel for ipadic: filename=ipadic-1.0.0-py3-none-any.whl size=13556704 sha256=bfe63bf0b9d3b3c6f55400dd64bddb8829d9eb8571254aa83a7b3336aadf05af
  Stored in directory: /root/.cache/pip/wheels/93/8b/55/dd5978a069678c372520847cf84ba2ec539cb41917c00a2206
  Building wheel for unidic (setup.py) ... done
  Created wheel for unidic: filename=unidic-1.1.0-py3-none-any.whl size=7403 sha256=33b34017474595e41ef7a43264d4c6bdd1a0c630de8b1d0d97d4125781e15bb1
  Stored in directory: /root/.cache/pip/wheels/cb/04/a2/659428f84ed1fa7257f8efb544b36043dd37a7c419e8ca711a
  Building wheel for unidic-lite (setup.py) ... done
  Created wheel for unidic-lite: filename=unidic_lite-1.0.8-py3-none-any.whl size=47658817 sha256=c382f2454b5032cdf0fd26452064dfd29a563fd572b5bca0bee092ef3eb88354
  Stored in directory: /root/.cache/pip/wheels/5e/1f/0f/4d43887e5476d956fae828ee9b6687becd5544d68b51ed633d
Successfully built seqeval ipadic unidic unidic-lite
Installing collected packages: wasabi, unidic-lite, sudachipy, plac, ipadic, sudachidict-core, spacy-alignments, rhoknp, fugashi, unidic, huggingface-hub, tokenizers, seqeval, transformers, datasets
  Attempting uninstall: wasabi
    Found existing installation: wasabi 1.1.3
    Uninstalling wasabi-1.1.3:
      Successfully uninstalled wasabi-1.1.3
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.11.0
    Uninstalling huggingface_hub-1.11.0:
      Successfully uninstalled huggingface_hub-1.11.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sentence-transformers 5.4.1 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.40.2 which is incompatible.
Successfully installed datasets-3.6.0 fugashi-1.5.2 huggingface-hub-0.36.2 ipadic-1.0.0 plac-1.4.5 rhoknp-1.3.0 seqeval-1.2.2 spacy-alignments-0.9.2 sudachidict-core-20260428 sudachipy-0.6.11 tokenizers-0.19.1 transformers-4.40.2 unidic-1.1.0 unidic-lite-1.0.8 wasabi-0.10.1

In [2]:
%pip uninstall -y peft

Found existing installation: peft 0.19.1
Uninstalling peft-0.19.1:
  Successfully uninstalled peft-0.19.1

### 6.2.1 データセット

#### データセットのダウンロード

###

In [3]:
from datasets import load_dataset

dataset = load_dataset("llm-book/ner-wikipedia-dataset")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

ner-wikipedia-dataset.py: 0.00B [00:00, ?B/s]

Downloading data:   0%|          | 0.00/4.04M [00:00<?, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

In [ ]:
from pprint import pprint

pprint(dataset)

DatasetDict({
    train: Dataset({
        features: ['curid', 'text', 'entities'],
        num_rows: 4274
    })
    validation: Dataset({
        features: ['curid', 'text', 'entities'],
        num_rows: 534
    })
    test: Dataset({
        features: ['curid', 'text', 'entities'],
        num_rows: 535
    })
})

In [5]:
pprint(dataset["train"]["text"][0:10])

['さくら学院、Ciao Smilesのメンバー。',
 '2008年10月5日、アウェーでのレクレアティーボ・ウェルバ戦でプリメーラ・ディビシオンでの初得点を決めた。',
 'ロシア政府に近いとされ、ロシアによるSNSを用いた世論操作を行った「オリギノのトロール工場」としても知られる。',
 '宮崎市立佐土原中学校は、宮崎県宮崎市佐土原町にある公立中学校。',
 'この時点で鈴屋は日本国内に約200店舗を有していたが、これらの事業は和議申請後にも継続されるとされた。',
 '高山祭は、岐阜県高山市で毎年開催される、4月14~15日の日枝神社例祭「春の山王祭」と、10月9~10日の櫻山八幡宮例祭「秋の八幡祭」の総称である。',
 '著名人では俳優のジョニー・デップが購入して所有している。',
 '1999年2月に日立造船因島工場においてヘリコプター格納庫内に実習用講堂を設置し、その他練習艦種別変更工事を行う。',
 'そこで、陳腐化した軽戦車や、鹵獲した戦車・車輌を改造するか、または旧型戦車の生産ラインを対戦車自走砲に切り替えるという決定がなされた。',
 '優等列車であるが、一部区間では各駅に停車となる列車種別で、1938年、京阪電鉄京阪本線に設定された区間急行が最初といわれている。']

In [6]:
pprint(list(dataset["train"])[:2])

[{'curid': '3638038',
  'entities': [{'name': 'さくら学院', 'span': [0, 5], 'type': 'その他の組織名'},
               {'name': 'Ciao Smiles', 'span': [6, 17], 'type': 'その他の組織名'}],
  'text': 'さくら学院、Ciao Smilesのメンバー。'},
 {'curid': '1729527',
  'entities': [{'name': 'レクレアティーボ・ウェルバ', 'span': [17, 30], 'type': 'その他の組織名'},
               {'name': 'プリメーラ・ディビシオン', 'span': [32, 44], 'type': 'その他の組織名'}],
  'text': '2008年10月5日、アウェーでのレクレアティーボ・ウェルバ戦でプリメーラ・ディビシオンでの初得点を決めた。'}]

#### データセットの分析

In [7]:
from collections import Counter
import pandas as pd
from datasets import Dataset

def count_label_occurrences(dataset: Dataset) -> dict[str, int]:
    """固有表現タイプの出現回数をカウント"""
    # 各事例から固有表現タイプを抽出したlistを作成する
    entities = [
        e["type"] for data in dataset for e in data["entities"]
    ]

    # ラベルの出現回数が多い順に並び替える
    label_counts = dict(Counter(entities).most_common())
    return label_counts

In [8]:
label_counts_dict = {}
for split in dataset:  # 各分割セットを処理する
    label_counts_dict[split] = count_label_occurrences(dataset[split])

# DataFrame形式で表示する
df = pd.DataFrame(label_counts_dict)
df.loc["total"] = df.sum()
display(df)

         train  validation  test
人名        2394         299   287
法人名       2006         231   248
地名        1769         184   204
政治的組織名     953         121   106
製品名        934         123   158
施設名        868         103   137
その他の組織名    852          99   100
イベント名      831          85    93
total    10607        1245  1333

#### スパンの重なる固有表現の存在を判定

In [9]:
def has_overlap(spans: list[tuple[int, int]]) -> int:
    """スパンの重なる固有表現の存在を判定"""
    # スパンを開始位置で昇順に並び替える
    sorted_spans = sorted(spans, key=lambda x: x[0])
    for i in range(1, len(sorted_spans)):
        # 前のスパンの終了位置が現在の開始位置よりも大きい場合、重なっているとする
        if sorted_spans[i-1][1] > sorted_spans[i][0]:
            return 1
    return 0

In [10]:
# 各分割セットでスパンの重なる固有表現がある事例数を数える
overlap_count = 0
for split in dataset:  # 各分割セットを処理する
    for data in dataset[split]:  # 各事例数を処理する
        if data["entities"]:  # 固有表現の存在しない事例はスキップする
            # スパンのみのlistを作成する
            spans = [e["span"] for e in data["entities"]]
            overlap_count += has_overlap(spans)
    print(f"{split}におけるスパンが重複する事例数: {overlap_count}")

trainにおけるスパンが重複する事例数: 0
validationにおけるスパンが重複する事例数: 0
testにおけるスパンが重複する事例数: 0

### 6.2.2 前処理

#### テキストの正規化

In [11]:
from unicodedata import normalize

# テキストに対してUnicode正規化を行う
text = "ＡＢＣABCａｂｃabcｱｲｳアイウ①②③123"
normalized_text = normalize("NFKC", text)
print(f"正規化前: {text}")
print(f"正規化後: {normalized_text}")

正規化前: ＡＢＣABCａｂｃabcｱｲｳアイウ①②③123
正規化後: ABCABCabcabcアイウアイウ123123

In [ ]:
text = "㈱、3㌕、10℃"
normalized_text = normalize("NFKC", text)
print(f"正規化前: {text}")
print(f"正規化後: {normalized_text}")

正規化前: ㈱、3㌕、10℃
正規化後: (株)、3キログラム、10°C

In [13]:
from unicodedata import is_normalized

count = 0
for split in dataset:
    for data in dataset[split]:
        # テキストが正規化されていない事例数をカウントする
        if not is_normalized("NFKC", data["text"]):
            count += 1
print(f"正規化されていない事例数: {count}")

正規化されていない事例数: 0

In [14]:
for split in dataset:
    pprint(split)
    for data in dataset[split]:
        pprint(data["text"])

'train'
'さくら学院、Ciao Smilesのメンバー。'
'2008年10月5日、アウェーでのレクレアティーボ・ウェルバ戦でプリメーラ・ディビシオンでの初得点を決めた。'
'ロシア政府に近いとされ、ロシアによるSNSを用いた世論操作を行った「オリギノのトロール工場」としても知られる。'
'宮崎市立佐土原中学校は、宮崎県宮崎市佐土原町にある公立中学校。'
'この時点で鈴屋は日本国内に約200店舗を有していたが、これらの事業は和議申請後にも継続されるとされた。'
'高山祭は、岐阜県高山市で毎年開催される、4月14~15日の日枝神社例祭「春の山王祭」と、10月9~10日の櫻山八幡宮例祭「秋の八幡祭」の総称である。'
'著名人では俳優のジョニー・デップが購入して所有している。'
'1999年2月に日立造船因島工場においてヘリコプター格納庫内に実習用講堂を設置し、その他練習艦種別変更工事を行う。'
'そこで、陳腐化した軽戦車や、鹵獲した戦車・車輌を改造するか、または旧型戦車の生産ラインを対戦車自走砲に切り替えるという決定がなされた。'
'優等列車であるが、一部区間では各駅に停車となる列車種別で、1938年、京阪電鉄京阪本線に設定された区間急行が最初といわれている。'
'1838年に曽国藩が湖南省試を受験したときの試験官を務めた。'
'金斗鎔は、労働者独自の運動に戻り、「労働者は祖国を持たない」という「共産党宣言」に基づいて民族的闘争を放棄することを主張した。'
'長野原支店では2018年冬期から毎年冬期の繁忙期輸送にジェイアールバス東北青森支店より新幹線E5系はやぶさカラーのハイデッカー車2台を借用して志賀草津高原線の臨時急行便で運行している。'
'同年マーカーはミルドレッド・コリンと結婚した。'
'日米地位協定というように、国家間の外交においても、条約等により両国間の役割、立場、権利、相手国及びその国民への処遇を規定する際、両国の立場を表す概念として地位と称される。'
('また、F3のメジャーイベントであるマスターズF3の大会スポンサーとなったり、フランスのミニテルにおいて「Marlboro Racing '
 'Service」と呼ばれるモータースポーツ情報の提供サービスを行っていたこともある。')
'ブリティッシュ・ホーム・チャンピオンシップは、イギリス国内の4地域の代表チームによって争われていたサッカー大会。'
'六甲山上にある1903年開場の日本最古のゴルフ倶楽部「神戸ゴルフ倶楽部」は冬季約4ヶ月間深い積雪に覆われるため、1年中プレーの出来るゴルフ場としてアーサー・H・グルームと親交のあった貿易商のウイリアム・J・ロビンソンによって1904年に神戸都心に近い魚崎町横屋に「横屋ゴルフ・アソシエーション」を開き、1914年には武庫郡鳴尾村の鳴尾浜に移転して「鳴尾ゴルフ・アソシエーション」を設けた。'
'1967年に大塚守康が株式会社大塚造園設計事務所設立。'
'日本芸能マネージメント事業者協会に加盟。'
'第一放送日曜午後担当の松本憲二は引き続き出演したが、若手や中堅クラスは「中央競馬ワイド中継」やグリーンチャンネルなど他局・他番組に転出していった。'
'旧国道56号は峠の登り口で新国道と分岐し、曲がりくねりながら上り下りする、昔ながらの峠道である。'
'大峠トンネルは福島県喜多方市と山形県米沢市を繋ぐ国道121号大峠道路のトンネル。'
'初代社長には鈴木憲太郎が就任した。'
'1947年日農内の社会、共産両党の路線対立が激化したため、副委員長であった野溝らは「日農主流体制確立に関する件」を提案し、日農は分裂する。'
'2017年12月10日に開催された「第7回AKB48紅白対抗歌合戦」に卒業前に審査員として参加した際、期待する小栗有以と向井地美音で渡辺の卒業ソング「サヨナラで終わるわけじゃない」、チームBメンバーで「チームB推し」の替え歌「まゆゆ推し」が歌われ、渡辺への感謝を示すパート構成がなされた。'
'翌年新国立劇場バレエ団から「ラ・シルフィード」主演のオファーを受けたマトヴィエンコは、相手役として将来有望な若手バレリーナを連れてきてほしいと依頼されたため、アナスタシアを選んだ。'
'社名は、角川グループの拠点である東京都千代田区富士見に由来する。'
'フレスポ四日市富田とは、大和リースが手がける、三重県四日市市西富田の三幸毛糸紡績富田工場跡地に2008年8月29日にオープンしたショッピングモールである。'
'しかしこの段階でもキリスト教信仰自体は許容されていた。'
'600×1000=60万が唐の兵力ということになる。'
'なお、ライクT3は経済産業省が行っている「クリーンエネルギー自動車導入促進対策費補助金」の対象となっているため、最大30万円の補助金を受けることができる。'
'武内樹とは長きにわたる親友であり、学生時のアルバイト仲間でもある。'
'1669年、フランス人探検家ロベルト・デ・ラ・サールは、ケベックからオンタリオ湖を上り、オハイオ川を下る探検の最中に、ヨーロッパ人としては初めてこの地に足を踏み入れた。'
'2017-18シーズンのロサンゼルス・レイカーズは、レイカーズのフランチャイズとしては70シーズン、NBAでは69シーズン、ロサンゼルス移転後58回目のシーズン。'
'彼は1906年の選挙でウィリアム・ランドルフ・ハーストを破り、州全体における唯一の共和党候補の当選者であった。'
'翌1916年公開のグリフィス監督の名作「イントレランス」には「古代バビロン篇」に端役で出演した。'
'2008年にはニューカッスル・ジェッツと七週間のゲストプレーヤー契約を結んだ。'
'1927年、福岡県で出光佐三の長男として生まれる。'
'タイタニック号が氷山に衝突した後、ベアとヘレンは彼女の母サリーと継父リチャード、エドウィンとガートルードのキンボール夫妻にボート甲板上で出会った。'
'したがってこれまでの結果をまとめると:階数がすべての自由"R"-加群に対して一意的に定義されることと、それがすべての有限生成自由"R"-加群に対して一意的に定義されることは同値である。'
'1972年、この会社は収用され、VEBドイツピアノ組合ライプツィヒに譲渡された。'
'「歌の花籠」「ハーモニカの友」「アコーディオン」「ハーモニカ研究」の四大雑誌を用紙統制令に基づき統合し、国民音楽社の名前で出版。'
'立ち技格闘技のシュートボクシングの創始者で会長のシーザー武志とも親交を結んでおり、中継番組の司会や、ゲスト解説者を務めている。'
'つまり、アリの姿をしていると、アリが仲間と間違えて寄ってくるので、これを捕食するのだというのである。'
'現在は建物内に郷土史や民族誌を専門とするカーサ・パイラル博物館が入っている。'
'2018年3月30日、県教育委員会は新たに柏陽高校と厚木高校を学力向上進学重点校に追加指定し、2018年4月1日から上記の4校体制で新制度が発足した。'
'フランス語形ではアデリーヌとなる。'
'1791年からバレエ作品の振付を手がけ始め、1801年にはウィーンで「プロメテウスの創造物」の振付を担当した。'
'大分市と湯平温泉のある湯平村間を鉄道で繋ぐ計画により1913年に設立された大湯鉄道株式会社により、1915年10月30日に大分市駅から小野屋駅までの間で開業した。'
'現役時代は外野手として活躍し、カンザスシティ・ロイヤルズで新人王を獲得後、ニューヨーク・ヤンキースに移籍。'
'松山湿原は、美深町の主要観光資源の一つである。'
'方位神は、それぞれの神に定められた規則に従って各方位を遊行する。'
'セカンド・アルバムの楽曲提供は作曲が井上ヨシマサ、高橋研、天野音彦、甲斐正人、根岸孝旨。'
'ハウは公職には就かなかったが、私的には元外務相のピアソンが党首選に出たときは支持し、1958年1月にピアソンが党首になった。'
'大滝本人による「Pap-Pi-Doo-Bi-Doo-Ba物語」を除いて、作詞はすべて松本隆が担当している。'
'1992年、千葉ロッテマリーンズにマイク・ディアズに代わる新外国人選手として入団し、6月に来日。'
'銃器を分類する語としては使われており、例えばドイツ連邦陸軍はホームページ上でG36をSturmgewehrと呼び、G3もSturmgewehrとして言及されることがある。'
'翌年、政緒の死去に伴い一家はそれぞれ菓子舗として独立、トミは両親と共に同郡川口村に移った。'
'JR北海道の主力列車である快速エアポートは以前、恵庭市内の全駅を通過していた。'
'胸壁筋は深胸筋とも呼ばれ、上肢とは関係なく横隔膜とともに呼吸運動をつかさどる筋群である。'
'アメリカ合衆国国勢調査局に拠れば、郡域全面積は889平方マイルであり、このうち陸地882平方マイル、水域は7平方マイルで水域率は0.70%である。'
'担当試合でレッドカードを出す割合が多いといわれており、2018年6月16日に行われたJ2第19節・松本山雅FCvs大分トリニータの試合後の公式記者会見では松本監督の反町康治がこの試合の清水のレフェリング、さらには主審の判定を評価するべき立場のマッチコミッショナーおよび審判アセッサーの質に対して苦言を呈す場面があった。'
'その一方で、「萌えドリル」シリーズやテレビアニメ版同様に、パロディ要素も多数盛り込まれており、中には他作品とのコラボレーションとして、関係先からの許諾を得たものも使われている。'
'このCDには同時に太田が本田のボーカル・トラックとデュエットしたバージョンと、愛・地球博の記念コンサートで本田と共演して以来交流の続いていた愛・地球博記念市民合唱団によるバージョンが併せて収録されている。'
'NHKを退きフリーとなるが、一時は資金を得るために借金をしなければならないほど苦しい生活を送っていた。'
'より小さな基本単位の組が提案されており、それは電場と磁場が同じ単位を持つ。'
'国連の推定によると、アンゴラ全土に残されている地雷は数百万発であるといわれている。'
'2014年の国勢調査によると、村の人口は406人であった。'
'2011年の供用開始が予定されていたものの、福島第一原子力発電所事故による警戒区域設定に伴い開通の目途が立っていなかったが、2014年12月6日の浪江インターチェンジ~南相馬インターチェンジ間の開通に伴い供用が開始された。'
'この事情を背景に、国鉄の関連企業として鉄道荷物会社が発足していくこととなった。'
'ヘミカルセランドは、他の分子との反応を防ぐことによって、その空洞内でゲストを安定化する。'
'同国への寄付などで金正日総書記の絶大な信頼を獲得したとされる。'
'かつて真鶴道路が日本道路公団により運営・管理されていた時期にはパーキングエリアとして、供食施設を持つ「真鶴売店」が併設されていた。'
'船田一雄は大正、昭和期の日本の実業家。'
'実際には「キュラソー入島」ビザは「名目上の行き先」であり、「途中経由地」であるアメリカや上海で旅行を終了するユダヤ人が多数であったのであるが、それを承知の上で、当時のリトアニア、在カウナス日本国領事杉原千畝は日本国通過ビザを発行した。'
'1968年7月のバアス党政権誕生から、2003年4月にサッダーム・フセイン政権が崩壊するまでは国権の最高機関であり、立法・行政・司法において最高意思決定機関の機能を有していた。'
'それにより、同年のJ1優勝チームである鹿島アントラーズは出場できなかった。'
'一方、西労組側は境線全駅での乗降客数は1日平均8000人で民営化時より増加しているとし、営業係数も300台に回復していると指摘した。'
'ある初期のSFカタログには1881年ににより書かれたファンタジー"Three Hundred Years Hence"が取り上げられている。'
'マサチューセッツ農科大学卒業後、1888年12月、日本政府の招聘により来日した。'
'後妻のユリは元衆議院議員米原昶の娘。'
'そして両陣営の対立が決定的となったのが船体の建造であった。'
'守備面では、連携プレーやスローイングに定評があるほか、内野の全ポジションを高いレベルでこなせるユーティリティープレイヤーである。'
'開会の辞は建設会長・今井徳順、工事ならびに会計報告・金子智、銅像製作報告・本山白雲、式辞・望月圭介、除幕、板垣正貫、奏楽、祝辞・浜口総理大臣代理、同祝辞・頭山満、同・犬養毅、同・栃木県知事、同・民政党支部長、同・政友会支部長、同・日光町長、家族代表謝辞・宮地茂秋の順に行われ、式後山内休憩所に於いて直会が開かれた。'
'しかし、その間にもビュート伯爵、ジョージ・グレンヴィル、イグリモント伯爵、ハリファックス伯爵らとの友好関係を維持した。'
'カシオペアは、アルバム「active」収録中、オーストラリア、メルボルン市内にあるクラブMETROで1992年2月26日にライブ行った。'
'アニーはフェビアン協会のために文章を書き始めた。'
'2004年12月26日に、ビルマプレートとインド・オーストラリアプレートの境界で断層がずれ、スマトラ島沖地震を引き起こした。'
'この箇所は1930年に「明治神宮水泳場」としてオープンしたもので、明治神宮国民体育大会の夏季水上競技会や、1948年、ロンドンオリンピックと同時期に開催された日本選手権水泳競技大会など、数多くの水泳競技会に使われた。'
'1975年5月、財団法人ヤマハ音楽振興会の主催による「第9回ポピュラーソング・コンテスト」に「傷ついた翼」が入賞した。'
'高校入試の難易度に対して大学進学実績がこれほどまでに優れている高校は他に類を見ない。'
'オルディングハウゼンにはアリガトール染色の本社がある。'
'その後、アメリカ軍はこの基地を放棄し、現在はBImAの所有となっている。'
'ベット・ミドラーはあるヴァージョンを彼女の映画"フォー・ザ・ボーイズ"のサウンドトラックのために録音した。'
'真木太郎は、日本の映像プロデューサー。'
'2015年に第3次安倍内閣によって提出され、国会で議論された平和安全法制について、同年9月16日放送の「NEWS23」にて、番組のアンカーである岸井成格が「安保法案は憲法違反であり、‟メディアとしても”廃案に向けて声をずっと上げ続けるべき」と発言した。'
'日本へは、トップ・ギアの撮影の他、英国BBC制作による新幹線のドキュメンタリー番組でも来日をしている。'
'TBSによる一連の番組は、「TBS宇宙プロジェクト「日本人初!宇宙へ」」と題し、テレビ・ラジオ双方で連日放送された。'
'明治製菓の元宣伝マンという経験から主題歌を作ることで、映画の宣伝効果が格段に上がることを知っていた。'
'フランシス・オビクウェルには及ばなかったものの、この種目のスウェーデン勢としては1962年ベオグラード大会で金メダルを獲得した以来、44年ぶり史上2人目となるメダルを獲得した。'
'モデル、女優でアーティストの土屋アンナとロックバンド・氣志團が、コラボレーションユニット「土屋アンナ<愛愛傘>氣志團」を結成してリリースしたシングル。'
'三菱UFJフィナンシャル・グループは2006年5月22日から、同行および同グループの三菱UFJ信託銀行両社の個人預金者を対象に、自動化手段を利用して行う両社及びじぶん銀行の本支店宛振込の手数料を一律無料化した。'
'繁殖力は非常に旺盛で、在来種を駆逐する侵略的外来種である。'
'1996年にミカエル・S・ベルベリアンによって設立された。'
'楽曲の質に対しては、音楽ライターの森朋之が音楽雑誌「CDジャーナル」および「VA」誌上にて「楽曲至上主義」の語をもって評価した。'
'しかしジェームズ・ブキャナン大統領は逆に、ミネソタ川に沿った彼らの保留地の北半分を没収し、スー族がパイプを作る伝統的な採石場があるミネソタ州パイプストーンの採石権まで奪った。'
'欧州や中国では数多くの北朝鮮専門旅行会社があるものの、日本では総代理店の中外旅行社の他、大同江ナビツアー、ジェイエス・エンタープライズ等数社に限られている。'
'アニメ監督の細田守、樋口真嗣とは飲み友達でプライベートでも交流がある。'
'リーダーのロバート・フリップはメンバーとの音楽性の相違から来るバンドの内紛に嫌気がさし、契約の残っていた1972年アイランド・ツアー終了の4月、キング・クリムゾンの解散を宣言する。'
'予選ステージは地理的に4つのグループに分けて行われ、各グループ上位がアラブカップ1998本大会に出場する。'
'残りのハイジャッカーの遺体片は特定に至らず、身元不明の遺体とともにメモリアルパークに埋葬されている。'
'ボストン交響楽団は歴史的に、ジェームズ・レヴァインを除いて外国の著名な指揮者を首席指揮者や客演指揮者に迎えており、ハンス・フォン・ビューローとの共演でチャイコフスキーの「ピアノ協奏曲第1番」の世界初演を行なったことは有名である。'
'2013年12月10日にリリースされ、 Firefox 27 のリリースをもってサポートが終了した。'
'関西電力、中部電力の原子炉建設と歩調を合わせ、運転開始予定は1970年度であった。'
'2014年には史上初めて、同一会場で全米オープンと全米女子オープンが開催された。'
'作戦機はすべてB-29で、実行者は第509混成部隊であった。'
'1982年10月18日、田尾は首位打者争いでトップの大洋の長崎啓二に1厘差まで迫っていた。'
'仙台トラストシティにある低層棟の1階〜3階および仙台トラストタワーの25階〜37階に入居し、客室数は292室、平均客室面積が約43m。'
('1970年には、日本万国博覧会で鉄鋼館の音楽監督を務め、このための作品として「クロッシング」、「四季」、テープ音楽"Years of '
 'Ear"を作曲、翌1971年には札幌オリンピックのためにIOCからの委嘱によってオーケストラ曲「冬」を作曲した。')
'この頃は雑誌「サンエス」で親友の佐藤一英とともに外国文学紹介のアルバイトをしていた。'
'伊那飛行場は、長野県伊那市六道原にかつて存在していた大日本帝国陸軍の飛行場、および同地に残る戦争遺跡。'
'2017年2月ユベントスとの契約を2018年まで延長した。'
'チェーホフは、1890年にはサハリンの流刑囚の生活を調査するためシベリア経由で現地に入り、カードを用いて徹底的に調べあげ、ルポルタージュ作品「サハリン島」を著している。'
'形式や文法的に可能な範囲は言語により大きく異なる。'
'2019年1月15日14時30分、武装グループがナイロビ市内のデュシットD2ホテルを襲撃した。'
'元々当線は1920年に入間川砂利株式会社という民間業者が敷設した専用鉄道を買収した路線で、その際に専用鉄道の免許も引き継がれたのである。'
'連結器はピン・リンク式で、開業当初は中心高さが349mmであったが、高屋線の開業とこれに伴う両備鉄道の客貨車の直通運転に備え、1925年1月15日付けで井笠鉄道在籍全車について同社車両と同じ501mmへの中心高さ引き上げ改造が実施された。'
'49歳の時、東京大正博覧会に「廓然無聖」他を出品。'
'2018年7月4日には、集英社のキャンペーン「ラブコメ満載!夏の女神フェア!!」に本作も参加し、単行本第1巻と第2巻のマイルド版が同年7月17日までの期間限定で無料公開された。'
'昇格当日のサンフランシスコ・ジャイアンツ戦に6番・左翼手で先発出場した。'
'英斂之は清朝の立憲君主改革を主張し続けており、「大公報」は革命による王朝打倒には批判的であった。'
"一つはジャニーズ事務所所属タレントが出演する「JOHNNYS' mini IsLAND」、もう一方は劇団四季の「キャッツ」が登場。"
'教育力による人材創出に力を入れ、AI、IoT、BigData、RPAなどハイエンドテクノロジーを活用したデジタルトランスフォーメーションと、クラウド・WEB・ITインフラストラクチャといったICTのベースとなるシステムインテグレーションを主な事業領域とする。'
'また、明治政府が江戸しぐさの摘発を行い、さらに多数の江戸っ子を虐殺した、江戸しぐさを広めるための秘密結社が存在したといった振興団体独自の歴史観が前提となっている。'
'1942年の総選挙で大政翼賛会の推薦を受け代議士に当選する。'
'同年、デンマークの郊外に補聴器の専門メーカー、ワイデックスが誕生した。'
'日本病理学会等が果たした役割は大きい。'
'ビール商品としては麦芽の使用率が低いため、日本で低税率系発泡酒が再度展開され始めた1990年代中盤頃の発泡酒商品の味に類似する面があり、自社製品同士の競合が懸念され、それが影響してアサヒビールは発泡酒市場への参入を躊躇したり難色を示したとされる。'
'世間は世界恐慌による大不景気へと突入していた。'
'また、後にシグネティックスがアーキテクチャ互換のSCC68070を製造した。'
'nanapiは、Supership株式会社が運営するノウハウの共有サービスの名称である。'
'狩集家は昔から遺産を当主となる1人にのみ相続するのだが実子4人はすでに亡くなっており、孫の代にあたる狩集汐路、狩集理紀之助、波々壁新音、赤峰ゆらの4人から選ばれることになる。'
'1年のブランクを経て現場復帰することとなった。'
'ベリーンも11回のレシーブで64ヤード、ランで13ヤードを獲得した。'
'エグゼクティブ・コミッティーのチェアはミルトン・チェン。'
'2008年北京五輪では決勝で2002年以降の主要大会で全て優勝してきたブラジルを破り、金メダルを獲得。'
'1998年6月にノキア、PSION、エリクソンが出資してシンビアンを設立。'
'「戦争と平和」は、1947年7月22日公開の日本映画である。'
'直後に本能寺の変が起きたため、天下人としての信長の隠居は実現せずに終わっている。'
'主制御器は、5500系ではゼネラル・エレクトリックと東京芝浦電気の技術提携によってMCM形パッケージ型制御装置が採用されていた。'
'1983年、中華人民共和国国務院は漢族地区仏教全国重点寺院に認定した。'
'中国人民解放軍海軍では、ロシアからM-22搭載の杭州級駆逐艦を導入して防空ミサイルの運用能力を獲得した。'
'2020年のオーストラリア国立会計監査局によると、2016年に試算された500億豪ドルを現在の為替レート換算した場合、897億豪ドルになると指摘した。'
'こうした批判は高まりをみせ、1996年2月から3月までにかけて新日本プロレスなどから取材拒否を受け、これを機に山本は団体の他にも週プロ読者やライバル誌であった「週刊ゴング」をも挑発するような紙面作りへと転換し、このことから販売部数を著しく減じることとなった。'
'落語芸術協会の若手真打4名で構成されたユニット「ヨセゲー」を結成している。'
'2011年9月、アルゼンチン代表との間で行われるアメリカ・スーパークラシックでブラジル代表メンバーに選出されたが個人的な理由から参加を辞退した。'
'1995年10月に東ハトより販売が開始された。'
'捕獲後、イギリス海軍に編入され「マルタ」と改名した。'
'1970年に住友銀行グループへ株式が譲渡され、以降はオフィスビルを中心とした賃貸不動産を近畿圏を中心として各地で展開している。'
'10月第1日曜日の有松天満社秋季大祭では3輌の山車が曳行される。'
'前年にナショナルリーグのワシントン・ナショナルズに在籍していた選手を中心に構成されていた。'
'スタンリー・クレイマーはアメリカ合衆国ニューヨーク出身の映画監督・映画プロデューサー。'
'ニコライ大公は1905年のロシア第一革命では極めて重要な役割を果たすことになった。'
'1992年には、マーベル・コミックの看板作家7人が独立し、アーティスト本人に作品の著作権が帰属するイメージ・コミックを設立した。'
'壬申の年の6月24日、吉野宮に隠棲していた大海人皇子は、兵を集めさせている東国に向かうため妻の鸕野讚良皇女と共に急いで出発した。'
('アルバムのリンダ・トンプソンが書いたトラック"Telling Me '
 'Lies"はカントリーで3位、アダルト・コンテンポラリーで25位に達し、1987年のベスト・カントリー・ソングしてグラミー賞にノミネートされた。')
'2020年からAC長野パルセイロへ完全移籍で加入。'
'通信サービスやコンピュータ・アプリケーション・サービスなどで、サービスの定義、内容、範囲、品質、達成目標、稼働率などを記述する。'
'EMU100型の営業最高時速は120キロで、ブレーキでの停車距離が時速100キロの莒光号より長いため営業運転以来踏切に絡む事故が多く、計5両が廃車された。'
'フロイド・ランディスの、ツール・ド・フランスにおけるドーピング騒動の余波を受けて、2006年シーズン限りでフォナックが解散したため、2007年に、現在も在籍する、AG2R・ラ・モンディアルに移籍。'
'有道出人は、アメリカ合衆国カリフォルニア州出身の日本国籍取得者、英会話教師、人権活動家、作家。'
'卒業後、拓殖大学に進むと、レスリング部監督であった須藤元気の薦めからプロ活動を自粛。'
'1765年光照寺の向かいに幕府天文方の司天台が移転してきたが、境内の林が観測に邪魔であったため、1782年には浅草に移転した。'
'2006年にパナソニックを退社後はフリーランスとなり、maximageに在籍の後、2008年に株式会社戯を創業。'
'倒幕後、慶應4年閏4月14日、新政府は銅銭の海外流出、銅地金の高騰、さらに市場での相場の実態を踏まえて、太政官布告第306号により鉄一文銭に対する銅銭および真鍮銭の増歩をさらに引き上げ以下のよう定めた。'
'なお、事件の当事者で切腹した池田虎之進の介錯を龍馬が行って、その血に刀の下緒を浸しながら下士の団結を誓ったという逸話が流布しているが、これは坂崎紫瀾の小説「汗血千里駒」のフィクションである。'
'1960年アメリカ合衆国大統領選挙において民主党候補者のジョン・F・ケネディはミサイル・ギャップの原因として共和党の国防政策を強く批判し、勝利の要因の1つとなった。'
'艦名は第二次世界大戦中、自由フランス軍に参加して海兵隊を指揮しイタリアで戦死したユーベル・アミヨ・ダンヴィユ海軍中佐に由来する。'
'マッケは上記2回の「青騎士」展に参加するとともに、1912年5月のゾンダーブント展、同年3月のベルリン新分離派展、1913年9月のドイツ秋季サロン展などの重要な展覧会に相次いで出品している。'
'2002年5月3日、東京武道館第一武道場で行われた第13回全日本新空手道選手権大会に出場。'
'日本経営税務法務研究会会長として2013年10月から、納税者の視点から法律に基づく適正な税務調査の実現による税務実務全体の改革を目指した税理士・弁護士対象の「税務調査士」資格認定を開始し、2019年までの累計参加者は440名を超えている。'
'最高裁判所は山田と今井に直接製作の中止を求め、完成すると配給予定の東映にも圧力をかけた。'
'1936年テイチクに移籍後、レコードを1枚出したのみで歌手活動を中止しその年の秋に帰国した。'
'2000年、丸の内駅舎を創建当初の姿に復原する方針がまとめられた。'
'2009年、13年間コーチを務めた鹿島を退団して京都サンガF.C.のGKコーチに就任。'
'特にロナルド・アクーニャ・ジュニアが昨年以上の活躍を見せるなど若手選手の活躍と、フレディ・フリーマンらベテラン勢の好調が上手く噛み合いチームは首位を守ったまま9月21日に2年連続で地区優勝を決めた。'
'また、Jリーグ・湘南ベルマーレの応援歌としても知られる。'
'第二次世界大戦後、旧・海軍大学校の跡地を毎日新聞社が払い下げを受け、子会社の東日興業が東日興業スタジオとして稼動していた撮影所を、1952年に東宝が同社を買収して設立した東京映画が東京映画撮影所として新たに開所した。'
'2012年にトップチーム昇格し、アイントラハト・ブラウンシュヴァイク戦でデビューした。'
'ピニェラ大統領、政府、チリ国民に賛辞を表する。'
'CPU2がアクセスを試みているかどうかに関わらず、DPRAMによってCPU1のためにテストが行われる。'
'エルビット・システムズとタレスUKの合弁事業として設立された合弁会社U-Tacsが主契約社となり、2007年7月15日に54機を発注、2010年6月の就役を目指したが、初飛行が2010年4月14日にずれ込み、最終的に就役は2014年となった。'
'クライアント側はキャラクターと衣装やポーズなどを選ぶだけで、旭プロダクション側が作画などを担当するのでコストが大幅に削減できる、という点を売りにしている。'
'内閣府は、総務省及び財務省と交付税及び譲与税配付金特別会計を、文部科学省、経済産業省及び環境省とエネルギー対策特別会計を、厚生労働省と年金特別会計を共管している。'
'マルコーニの発明した無線電信に興味を惹かれ、グリエルモ・マルコーニに宛て就職を依頼する手紙を書くが返事は来なかった。'
'本記事ではマツやモミの木を模して作られた人工樹のクリスマスツリーについて説明する。'
'その他に、藤本龍児によると、1960年代から「バイブル・ベルト」と呼ばれる南部は、工業化・都市化が進み、教育水準が向上した。'
'翌2月20日には、国際プロレスが会見を開き、東郷との絶縁並びに、外国人招聘ルートをヨーロッパに変更することを発表した他、東郷と外国人選手全員も、2月23日に記者会見を開き、国際との絶縁並びに外国人選手全員を帰国させることを発表した。'
'ユナイテッドヘルスケアには4つの部門がある。'
'しかしながら排気ガス規制自体は徐々に進み、アメリカ本土においては1995年にはマスキー法で定められた基準に達したが、を独自に制定するカリフォルニア州を除いて、アメリカ合衆国連邦政府には日本の車検制度のような強制力を持った排ガス検査制度がない為、新車登録を済ませてしまえば後は違法改造されてもまず検挙されることはなく、ザル法であるという意見もある。'
'その後、インディ500で負傷したヴィトール・メイラの代役としてA.J.フォイト・エンタープライズに移籍し、シーズン終了まで参戦。'
'これに対し、香港政府は林鄭月娥が18日の記者会見ですでに謝罪したと述べ、これ以上の返答をしない方針を明らかにした。'
'2019年11月20日、メジャーリーグサッカーのポートランド・ティンバーズに加入することが発表された。'
'毎月27日発売。'
'1936年、オリジナル・ディキシーランド・ジャズ・ファイヴと名乗って再結成し、1938年まで活動。'
"7月21日に、小林武史と櫻井和寿が主催の野外フェスティバル、ap bank fes '08に初出演。"
'1920年に五社公園に浜松市立図書館が開館したが、太平洋戦争末期の浜松空襲で焼失した。'
'一般には内閣府はおおむね中央省庁再編前の総理府の後継機関と考えられているが、再編前は上位法である国家行政組織法の規定を受けて個別法としての各府省の設置法が存在するという「府省横並び」の関係にあったのに対し、再編後は内閣府設置法のみ国家行政組織法の対象外とされたため、内閣府は「他省より上位の格」を有する機関と位置づけられている。'
'その後の数年間、ロングエーカーは書店で働いていたが、ワトソンはこの少年が肖像画の技法に優れていると認識した。'
'コーヴァルチック社は軌道を撤去してスクラップとして売却する計画を2008年に発表した。'
'ジョゼフ・マイケル・ストラジンスキーはアメリカの作家でテレビ・プロデューサー。'
'但し耳川の戦いの頃に穆左は嫡子の規久に任せ、自身は大隅の堅利に住んだ。'
'ところが、実際に日韓W杯が終了すると、日本W杯組織委員会は約130億円の黒字を計上した。'
'2011年の神奈川県議選では民主党の推薦も受けて出馬したが、自由民主党元職の古沢時衛に敗れ、落選。'
'野戦軍は実戦部隊を管理する組織ではあるが、野戦軍司令部そのものが作戦指揮を執ることは無い。'
'1790年にテルフォードはロンドンからホリーヘッドに向かう道路上、モントフォードでセヴァーン川にかかっている橋を設計した。'
'依頼によりあらゆる男女を別れさせる「別れさせ屋」の活躍を描いたドラマ。'
'当初、2013年4月までに1万店舗の開設が目標だったが、わずか1カ月で目標の1万店舗を達成した。'
'1951年9月1日、「小樽タイムス」を合併し、1958年1月3日には旭川の「北海日日新聞」を、5月には釧路の「東北海道新聞」を合併。'
'第67回ヴェネツィア国際映画祭のコンペティション部門で上映され、銀獅子賞と金オゼッラ賞を受賞した。'
'ジャン=バティスト・ド・ロシャンボー将軍が率いるフランス陸軍アメリカ派遣部隊が1780年から1782年後期まで使用したが、特に1781年のヨークタウンの戦いが有名である。'
'戦後の日本では、連合国軍最高司令官総司令部占領下で学制改革が行われ新制大学が発足した。'
'入会方法は、ユナイテッド航空のWebサイトか、電話か、ユナイテッド航空またはコパ航空の空港カウンターやラウンジなどの営業所、ユナイテッド航空またはコパ航空の機内などで、備え付けの申込用紙に記入して、提出すると入会できる。'
'適切な医療を実現する医師国会議員連盟は、日本の超党派の議員連盟の1つ。'
'田村の離党・民主党入りが、とかく内紛続きだった自民党県連を「反田村」で一致団結させ、結束強化につながったことが背景にあるとの皮肉な見方もなされている。'
'その後KLMオランダ航空は植民地であるジャワとの長距離定期便に就航させた。'
'1960年のF1世界選手権に組み込まれて開催されたが、F1世界選手権として開催されたのはこの年が最後となった。'
'2006年1月7日、デポルティーボ・ラ・コルーニャ戦でデビューした。'
('2008年12月4日、多額の寄付などを通じてインディアナ大学ブルーミントン校ロースクールに貢献のあったMichael S. '
 'Maurer氏の名を冠して、Maurer School of Lawと称されることとなった。')
'2001年に報道部副部長を最後に宮崎放送を退社し、民主党・社会民主党推薦で参議院議員選挙に出馬するも落選した。'
'Google Nowと異なり、Googleの自然言語処理アルゴリズムを用いてアシスタントは双方向の会話が出来るようになっている。'
'宝永4年には、宝永地震の影響による石垣修理などが成されている。'
'北上回漕会社は、岩手県盛岡市にあった舟運業者。'
'その後、イギリスはアワド太守シュジャー・ウッダウラにミール・カーシムを捕えさせ投獄し、翌1765年8月16日にイギリスは戦後処理としてアラーハーバード条約を締結した。'
'株式会社ヤマグチ薬局は、日本の薬局である。'
'ブレーブスのフレッド・ヘイニー新監督はコンリーを控えめに起用した。'
'男子部門の決勝戦は、マーティン・エァダムズが、6-0と、リードしており、余裕の状況であった。'
'日本ポリグル株式会社は、ポリグルタミン酸の製造販売を中心に、水質浄化事業を行っている会社。'
'2015年8月30日のCDミランデス戦で、プロ初ゴールを記録。'
'さらに連合軍はワウ方面への補給のため、ニューギニア島南岸からオーウェンスタンレー山脈を越えてワウへ至る幅員5~6メートルの道路を完成させつつあった。'
'現在の古墳域は日の里12号公園内に位置し、他の円墳2基とともに保存されている。'
'ロシアと大日本帝国との関係は日に日に悪化しており、ウラジオストク巡洋艦隊は来るべき開戦に備え、朝鮮海峡にて訓練を積んだ。'
'これに伴いオーストラリアのニューサウスウェールズ植民地政府に付随する一地方であったニュージーランドはイギリス直轄の植民地となり、初代総督はそのまま代理総督だったホブソンが引き継いだ。'
'指導教授の紹介と原煕推挙によって、同年明治神宮造営局に奉職。'
'その後ポーランド銀行という名称を持つ銀行が設立され、第二次世界大戦後のポーランドの計画経済を運営することが認められていた。'
'番組の企画者は、「NHK紅白歌合戦」も企画立案したNHK音楽部のプロデューサー、三枝嘉雄。'
'これまでに多田悦子や名城信男らがアマチュアと公開スパーリングを行っており、大会運営や日本代表の活動などで協力を約束している。'
'かえしにさらに味醂を加え寝かせた物を御膳がえしまたは上がえしといい、ざる蕎麦用のざる汁に使われる。'
'世界詩歌記念日は、国際連合のユネスコが文芸の増進のために1999年に取り決めた詩を記することを通じて言語の多様性を促進し、危機に瀕する言語による表現を可能とすることを目的とする日である。'
'第3期には学窓から直接採用された者もおり、第4期に採用された者は全員が在学中の学徒からであった。'
'1980年4月、イランにおける在テヘラン米大使館人質救出作戦が失敗に終わると、その原因究明と再発防止策検討の為に設置されたホロウェイ委員会は専任の特殊作戦航空部隊の新設を含む特殊作戦能力の再編を軍上層部に命じ、それを受けてアメリカ陸軍はタスクフォース160を創設した。'
'なおほぼ同じ時期に、村田真などの人々も、XML Schemaとは別の新しいスキーマ言語RELAXを開発していた。'
'中古車は1991年に神奈川中央交通の車両を購入したのが最初だったが、譲受車の導入はJRバスの中でも最も早かった。'
'24日午後8時、米海軍査問委員会報告書が発表される。'
'2017年3月、FC町田ゼルビアへ期限付き移籍。'
'2012年7月にはUMCとファウンドリ契約を結んだ。'
'2010年7月、BNYメロンは地元ピッツバーグのPNCから投資ファンドを買収した。'
'2014年2月27日、ドイツのバイエル・レバークーゼンに5年契約で移籍することが決まった。'
'しかし、1982-83シーズンは無冠に終わり、1983-84シーズンはマヌエル・サンチス・オンティジュエロ、マルティン・バスケス、ミゲル・パルデサ、エミリオ・ブトラゲーニョがトップチームの試合に初出場するも無冠に終わる。'
'同様に、松原ICで流出入し近畿道東大阪南IC以遠または西名阪道を通行する場合、阪和道の料金は不要である。'
'高校と大学で野球経験のある代表者が、就職後に勤務地の長野県で信濃グランセローズに接したことで、自らの出身地である茨城県に球団を作る構想を抱き、構想の発表から約2年をかけて加盟を実現させた。'
'1979年にイラン革命が興ると、キプロス問題で冷え込んでいたアメリカ合衆国との関係も好転、1980年には軍事クーデターが起こり、二院制が一院制に変わるなどの憲法改正が行われ、治安と経済が改善、程なく民政移管が行われた。'
'2007年3月、ペトリーはライプツィヒ市プラグヴィッツ地区にプラスチック加工会社プリンベント・ゲーエムベーハーという有限会社を設立した。'
'兄弟は、姉のジュリー・ミッチャム、そして、同じ俳優となった兄のロバート・ミッチャムがいる。'
'いかりや逝去の際、バンド時代から親交の深かった立川談志が、追悼コメントで「ヤツを今時「長兵衛」と呼ぶのも、もう俺ぐらいしかいない」と語っていた。'
'ただ日本自動車連盟は、1987年までF2車両による選手権を継続し、1988年からF3000に移行する考えであった。'
'GNU Free Documentation Licenseについては、Debianはディストリビューション内の文書についてもDFSGを適用すると決めた。'
'流域一体は水田が多く、取水堰として樋遣川堰が設置され農業用水として利用されている一方で、同時に農業排水路としても機能している。'
'その後、湯布院町商工会長や由布院温泉観光協会会長を歴任。'
'有名な華族軍人としては、陸軍では前田利為や町尻量基、海軍では醍醐忠重や小笠原長生らがいる。'
'毎号、政治家本人へのインタビュー記事が掲載されることで知られる。'
'フランスでは、フランス電力公社とトヨタ自動車が道路、車道、駐車場にPHEVのための充電ポイントを設置している。'
'新韓党は、民政のための政権交代を当面の最大目標に設定し、韓国各地で共和党政権の非理を暴露、糾弾する集会を開催するなどの、与党に対する強硬な闘争を展開した。'
'監督はジョシュ・トランクが務め、マイルズ・テラー、ケイト・マーラ、マイケル・B・ジョーダン、ジェイミー・ベル、トビー・ケベルが主要キャラクターを演じる。'
'ワンハンドレッドヒルズは、千葉県千葉市緑区あすみが丘六丁目で東急不動産が開発・分譲した宅地の名称である。'
'タバコ小売店営業をしていた1931年6月に国家社会主義ドイツ労働者党に入党する。'
'江戸幕府は慶安元年に「風紀を乱す」という理由で勧進相撲禁止令を出している。'
'ホーナー社のメロディカは、日本でも1959年3月に娯楽雑誌の記事で紹介され、1960年初頭から輸入販売が始まった。'
'千總は、京都府京都市中京区にある京友禅の老舗。'
'しかし、その当日に発生した関東大震災で深川地区は壊滅。'
'またアフガニスタンでの国際治安支援部隊や不朽の自由作戦にも多くの国が参加している。'
'また作品展示として日本人漫画家210名、韓国、台湾、香港、中国の漫画家100名の作品を展示した「東アジアMANGA原画展」が9月1日から9月29日までいわき市立美術館で開催、ロビーには手塚治虫の特別コーナーが設置され、日本のストーリーマンガ50年を象徴する構成とされた。'
'全校生徒が少なく全学年2学級である。'
'その後、人々は天狗に感謝して権現神社のお祭りには太鼓を叩いたり、天狗を祀った神輿をかついだりしてきた。'
'2018年アジアパラ競技大会は2018年に開催された第3回アジアパラ競技大会。'
'石灰石の大鉱床として知られる武甲山のふもとの地に、秩父セメントが創業したのは1923年で元々の工場は秩父市の市街地に近いところにあったが、朝鮮戦争勃発による特需を受け、生産力を増強するため、別の敷地に新しい工場を建てる計画が持ち上がる。'
'このゲームは欧州にてから発売されたAmiga、Atari ST用ゲームソフト「"Striker"」が元になっている。'
'丸の内パークビルディング地下1階から4階、低層棟、三菱一号館、一号館広場からなる商業ゾーンは総称として丸の内ブリックスクエアと名付けられている。'
'2015年5月7日、第一汽車の新董事長に東風汽車の前董事長だった徐平が任命された。'
'1899年1月20日に奈良駅における連絡に関して大阪鉄道・関西鉄道と契約が成立し、2月11日から貨物の連絡輸送が奈良-京終間で開始された。'
'一連のアル=アッザーウィーの再台頭は、1996年から実施された国連による「石油と食糧の交換計画」が開始されたことが大きな要因とされる。'
'こうして東京横浜電鉄が生まれた。'
'ヤンキースでは、左打ちのダグ・ミントケイビッチとファーストのポジションで併用される見通しだったが6月16日にピッツバーグ・パイレーツへ移籍。'
'高松中央郵便局は、香川県高松市にある郵便局。'
'クレーンの運搬にはチリ海軍の協力を得ている。'
'スウィーニー・トッドは、19世紀イギリスの伝説、スウィーニー・トッドを題材としたミュージカルである。'
'EXILEのダンスパフォーマンスのレベルの高さと年齢的な体力低下に伴い、岡村本人はライオンキングを超えるハードさと番組中語っていた。'
'ダニス・タノヴィッチはユーゴスラビア出身の映画監督・脚本家である。'
'このモデル名はAMCの2座スポーツカーAMXを思い起こさせる有名な車名の復活であった。'
'長崎空港へは西肥バスの特急バスと乗合ジャンボタクシーが運行されている。'
'脚本家として剣山象、高橋伴の名義で活動したこともある。'
'ザカライア・チャンドラーは、アメリカ合衆国ミシガン州の政治家であり、デトロイト市長、ミシガン州選出のアメリカ合衆国上院議員を4期、およびユリシーズ・グラント大統領政権でアメリカ合衆国内務長官を務めた。'
'また、超音速機に関しては、陸上飛行時に問題となるソニックブーム低減に向けた研究などで、NASAとの間での共同研究が実施される。'
'ジーメンスはこれを「高架から降ろされた高架線」と名付けた。'
'ムバンダカ空港は、コンゴ民主共和国赤道州ムバンダカにある空港。'
'1935年12月15日に釈放され、すぐに以前の本業に戻って1956年に亡くなるまでカポネの後継者フランク・ニッティ、ポール・リッカ、マレー・ハンフリーズらとシンジケートの仲間と仕事を続けた。'
'三次救急を担う大阪府立中河内救命救急センターが隣接し、道路の反対側には一次救急に対応する東大阪市休日急病診療所があるため、一次・二次・三次の窓口が密接しており、特に中河内救命救急センターとは連携がなされている。'
'グリフィス大学は、オーストラリア国内の最優秀講師賞を得た大学としても有名である。'
'主に自動車用ブレーキを中心に生産し、トヨタ、日産や米GMを中心に各完成車メーカーへの供給を行っている。'
'ロードレース世界選手権の軽量級クラスで活躍し、50ccクラスと125ccクラスでのべ13もの世界タイトルを獲得した。'
'702年、壬申の乱で功労があった豪族をねぎらうため持統天皇が村積山に訪れ、手ずから植えたものがこのしだれ桜とされる。'
'また、2010年5月に東海東京証券との連結子会社で、九州の地銀初となる証券子会社の西日本シティTT証券が新たに発足した。'
'2007年4月に破綻した英会話学校NOVAの2007年3月決算で、係争事件を「企業の存続に重大な影響を与えるリスク」として開示していなかったことについて、不適切な情報開示として当時の担当監査法人であったあずさ監査法人が公認会計士協会の調査を受けている。'
'2017年に舞台化作品が上演。'
'1903年、Wigham Richardson社はSwan and Hunter社と特別に合併した。'
'以後、数々のコンクールに招待され、各地への演奏旅行も行う。'
'1943年12月に、事務所を改組して田中土建工業を設立した。'
'チャレンジャー号爆発事故によってこの計画も中止されたため、緊急着陸地のリストから外された。'
'でも、チームのみんなが僕のやりたかったことをサポートしてくれた。'
'帝政ローマ支配下の属州ブリタンニアではキリスト教の布教がローマ人の入植とともに広まっていたが、5世紀にブリタンニアが放棄されると廃れてしまっていた。'
'千葉市が推進する千葉中央第六地区第一種市街地再開発地区に近接したセントラルプラザ跡地の再開発事業によって建設された。'
'1991年から米国NASDAQ上場バイオベンチャー企業のCell Genesys, Inc.社外取締役を兼任。'
'同宗派の真龍寺・宝林寺とともに「三軒寺」を称している。'
'尚、これは定訳があるわけではなく、「働けば自由になれる」「労働は人間を自由にする」「労働で自由を得られる」「労働は自由への道」「労働すれば自由になれる」「労働は自由の元」など様々に訳される。'
'1930年代半ばからすくなくとも1939年まで、ラウリーはベリック・アポン・ツイードで年次休暇をすごした。'

#### テキストのトークナイゼーション

In [15]:
from transformers import AutoTokenizer

model_name = "cl-tohoku/bert-base-japanese-v3"
tokenizer = AutoTokenizer.from_pretrained(model_name)

subwords = "/".join(tokenizer.tokenize(dataset["train"][0]["text"]))
characters = "/".join(dataset["train"][0]["text"])
print(f"サブワード単位: {subwords}")
print(f"文字単位: {characters}")

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/251 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

サブワード単位: さくら/学院/、/C/##ia/##o/Sm/##ile/##s/の/メンバー/。
文字単位: さ/く/ら/学/院/、/C/i/a/o/ /S/m/i/l/e/s/の/メ/ン/バ/ー/。

#### 文字列とトークン列のアライメント

In [16]:
text = "さくら学院"

In [ ]:
from spacy_alignments.tokenizations import get_alignments

# 文字列のlistを獲得する
characters = list(text)
# テキストを特殊トークンを含めたトークンのlistに変換する
tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(text))
# 文字列のlistとトークンのlistのアライメントを取る
char_to_token_indices, token_to_char_indices = get_alignments(characters, tokens)

# 確認
print(f"文字のlist: {characters}")
print(f"文字に対するトークンの位置: {char_to_token_indices}")

print(f"トークンのlist: {tokens}")
print(f"トークンに対する文字の位置: {token_to_char_indices}")

文字のlist: ['さ', 'く', 'ら', '学', '院']
文字に対するトークンの位置: [[1], [1], [1], [2], [2]]
トークンのlist: ['[CLS]', 'さくら', '学院', '[SEP]']
トークンに対する文字の位置: [[], [0, 1, 2], [3, 4], []]

#### 系列ラベリングのためのラベル作成

In [ ]:
text = "大谷翔平は岩手県水沢市出身"
entities = [
    {"name": "大谷翔平", "span": [0,4], "type": "人名"},
    {"name": "岩手県水沢市", "span": [5,11], "type": "地名"},
]

In [19]:
from transformers import PreTrainedTokenizer

def output_tokens_and_labels(
    text: str,
    entities: list[dict[str, list[int] | str]],
    tokenizer: PreTrainedTokenizer,
) -> tuple[list[str], list[str]]:
    """トークンのlistとラベルのlistを出力"""
    # 文字のlistとトークンのlistのアライメントを取る
    characters = list(text)
    tokens = tokenizer.convert_ids_to_tokens(tokenizer.encode(text))
    char_to_token_indices, _ = get_alignments(characters, tokens)

    # "0"のラベルで初期化したラベルのlistを作成する
    labels = ["O"] * len(tokens)
    for entity in entities:  # 各固有表現で処理する
        entity_span, entity_type = entity["span"], entity["type"]
        start = char_to_token_indices[entity_span[0]][0]
        end = char_to_token_indices[entity_span[1] - 1][0]
        # 固有表現の開始トークンの位置に"B-"のラベルを設定する
        labels[start] = f"B-{entity_type}"
        # 固有表現の開始トークン以外の位置に"B-"のラベルを設定する
        for idx in range(start+1, end+1):
            labels[idx] = f"I-{entity_type}"
    # 特殊トークンの位置にはラベルを設定しない
    labels[0] = "-"   # [CLS]
    labels[-1] = "-"  # [SEP]
    return tokens, labels

In [ ]:
# トークンとラベルのlistを出力する
tokens, labels = output_tokens_and_labels(text, entities, tokenizer)
# DataFrameの形式で表示する
df = pd.DataFrame({"トークン列": tokens, "ラベル列": labels})
df.index.name = "位置"
display(df.T)

位置        0     1     2     3  4     5     6     7     8   9      10
トークン列  [CLS]    大谷     翔   ##平  は    岩手     県    水沢     市  出身  [SEP]
ラベル列       -  B-人名  I-人名  I-人名  O  B-地名  I-地名  I-地名  I-地名   O      -

## 6.2.3 評価指標

#### seqevalライブラリを用いた評価スコアの算出

In [21]:
from typing import Any
from seqeval.metrics import classification_report

def create_character_labels(
    text: str,
    entities: list[dict[str, list[int] | str]]
) -> list[str]:
    """文字ベースでラベルのlistを作成"""
    # "o"のラベルで初期化したラベルのlistを作成する
    labels = ["O"] * len(text)
    for entity in entities:  # 各固有表現を処理する
        entity_span, entity_type = entity["span"], entity["type"]
        # 固有表現の開始トークンの位置に"B-"のラベルを設定する
        labels[entity_span[0]] = f"B-{entity_type}"
        # 固有表現の開始トークン以外の位置に"B-"のラベルを設定する
        for i in range(entity_span[0]+1, entity_span[1]):
            labels[i] = f"I-{entity_type}"
    return labels

def convert_results_to_labels(
    results: list[dict[str, Any]]
) -> tuple[list[list[str]], list[list[str]]]:
    """正解データと予測データのラベルのlistを作成"""
    true_labels, pred_labels = [], []
    for result in results:  # 各事例を処理する
        # 文字ベースでラベルのリストを作成してlistに加える
        true_labels.append(
            create_character_labels(result["text"], result["entities"])
        )
        pred_labels.append(
            create_character_labels(result["text"], result["pred_entities"])
        )
    return true_labels, pred_labels

In [22]:
results = [
    {
        "text": "大谷翔平は岩手県水沢市出身",
        "entities": [
            {"name": "大谷翔平", "span": [0, 4], "type": "人名"},
            {"name": "岩手県水沢市", "span": [5, 11], "type": "地名"},
        ],
        "pred_entities": [
            {"name": "大谷翔平", "span": [0, 4], "type": "人名"},
            {"name": "岩手県", "span": [5, 8], "type": "地名"},
            {"name": "水沢市", "span": [8, 11], "type": "施設名"},
        ],
    }
]

# 正解データと予測データのラベルのlistを作成する
true_labels, pred_labels = convert_results_to_labels(results)
# 評価結果を取得して表示する
print(classification_report(true_labels, pred_labels))

              precision    recall  f1-score   support

          人名       1.00      1.00      1.00         1
          地名       0.00      0.00      0.00         1
         施設名       0.00      0.00      0.00         0

   micro avg       0.33      0.50      0.40         2
   macro avg       0.33      0.33      0.33         2
weighted avg       0.50      0.50      0.50         2

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
from seqeval.metrics import f1_score, precision_score, recall_score

def compute_scores(
    true_labels: list[list[str]],
    pred_labels: list[list[str]],
    average: str
) -> dict[str, float]:
    """適合率、再現率、F値を算出"""
    scores = {
        "precision": precision_score(true_labels, pred_labels, average=average),
        "recall": recall_score(true_labels, pred_labels, average=average),
        "f1-score": f1_score(true_labels, pred_labels, average=average)
    }
    return scores

In [24]:
# 適合率、再現率、F値のマイクロ平均を算出する
print(compute_scores(true_labels, pred_labels, "micro"))

{'precision': np.float64(0.3333333333333333), 'recall': np.float64(0.5), 'f1-score': np.float64(0.4)}

## 6.3 固有表現認識モデルの実装

### 6.3.1 BERTのファインチューニング

#### ラベルとIDを対応付けるdictの作成

In [ ]:
import torch

def create_label2id(
    entities_list: list[list[dict[str, str | int]]]
) -> dict[str, int]:
    """ラベルとIDを紐づけるdictを作成"""
    # "O"のIDには0を割り当てる
    label2id = {"O": 0}
    # 固有表現タイプのsetを獲得して並び替える
    entity_types = set(
        [e["type"] for entities in entities_list for e in entities]
    )
    entity_types = sorted(entity_types)
    for i, entity_type in enumerate(entity_types):
        # "B-"のIDには奇数番号を割り当てる
        label2id[f"B-{entity_type}"] = i * 2 + 1
        # "I-"のIDには偶数番号を割り当てる
        label2id[f"I-{entity_type}"] = i * 2 + 2
    return label2id

In [26]:
# ラベルとIDを紐付けるdictを作成する
label2id = create_label2id(dataset["train"]["entities"])
id2label = {v: k for k, v in label2id.items()}
pprint(label2id)
pprint(id2label)

{'B-その他の組織名': 1,
 'B-イベント名': 3,
 'B-人名': 5,
 'B-地名': 7,
 'B-政治的組織名': 9,
 'B-施設名': 11,
 'B-法人名': 13,
 'B-製品名': 15,
 'I-その他の組織名': 2,
 'I-イベント名': 4,
 'I-人名': 6,
 'I-地名': 8,
 'I-政治的組織名': 10,
 'I-施設名': 12,
 'I-法人名': 14,
 'I-製品名': 16,
 'O': 0}
{0: 'O',
 1: 'B-その他の組織名',
 2: 'I-その他の組織名',
 3: 'B-イベント名',
 4: 'I-イベント名',
 5: 'B-人名',
 6: 'I-人名',
 7: 'B-地名',
 8: 'I-地名',
 9: 'B-政治的組織名',
 10: 'I-政治的組織名',
 11: 'B-施設名',
 12: 'I-施設名',
 13: 'B-法人名',
 14: 'I-法人名',
 15: 'B-製品名',
 16: 'I-製品名'}

#### データの前処理

In [27]:
from transformers.tokenization_utils_base import BatchEncoding

def preprocess_data(
    data: dict[str, Any],
    tokenizer: PreTrainedTokenizer,
    label2id: dict[int, str]
) -> BatchEncoding:
    """データの前処理"""
    # テキストのトークナイゼーションを行う
    inputs = tokenizer(
        data["text"],
        return_tensors="pt",
        return_special_tokens_mask=True,
    )
    inputs = {k: v.squeeze() for k, v in inputs.items()}

    # 文字のlistとトークンのlistのアライメントをとる
    characters = list(data["text"])
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"])
    char_to_token_indices, _ = get_alignments(characters, tokens)

    # "O"のIDのlistを作成する
    labels = torch.zeros_like(inputs["input_ids"])
    for entity in data["entities"]:  # 各固有表現を処理する
        start_token_indices = char_to_token_indices[entity["span"][0]]
        end_token_indices = char_to_token_indices[entity["span"][1]-1]
        # 文字に対応するトークンが存在しなければスキップする
        if (len(start_token_indices) == 0 or len(end_token_indices) == 0):
            continue
        start, end = start_token_indices[0], end_token_indices[0]
        entity_type = entity["type"]
        # 固有表現の開始トークンの位置に"B-"のIDを設定する
        labels[start] = label2id[f"B-{entity_type}"]
        # 固有表現の開始トークン以外の位置に"I-"のIDを設定する
        if start != end:
            labels[start+1:end+1] = label2id[f"I-{entity_type}"]
    # 特殊トークンの位置のIDは-100とする
    labels[torch.where(inputs["special_tokens_mask"])] = -100
    inputs["labels"] = labels
    return inputs

In [28]:
# 訓練セットに対して前処理を行う
train_dataset = dataset["train"].map(
    preprocess_data,
    fn_kwargs={
        "tokenizer": tokenizer,
        "label2id": label2id,
    },
    remove_columns=dataset["train"].column_names,
)
# 検証セットに対して前処理を行う
validation_dataset = dataset["validation"].map(
    preprocess_data,
    fn_kwargs={
        "tokenizer": tokenizer,
        "label2id": label2id,
    },
    remove_columns=dataset["validation"].column_names,
)

Parameter 'fn_kwargs'={'tokenizer': BertJapaneseTokenizer(name_or_path='cl-tohoku/bert-base-japanese-v3', vocab_size=32768, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}, 'label2id': {'O': 0, 'B-その他の組織名': 1, 'I-その他の組織名': 2, 'B-イベント名': 3, 'I-イベント名': 4, 'B-人名': 5, 'I-人名': 6, 'B-地名': 7, 'I-地名': 8, 'B-政治的組織名': 9, 'I-政治的組織名': 10, 'B-施設名': 11, 'I-施設名': 12, 'B-法人名': 13, 'I-法人名': 14, 'B-製品名': 15, 'I-製品名': 16}} of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
WARNING:datasets.fingerprint:Parameter 'fn_kwargs'={'tokenizer': BertJapaneseTokenizer(name_or_path='cl-tohoku/bert-base-japanese-v3', vocab_size=32768, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}, 'label2id': {'O': 0, 'B-その他の組織名': 1, 'I-その他の組織名': 2, 'B-イベント名': 3, 'I-イベント名': 4, 'B-人名': 5, 'I-人名': 6, 'B-地名': 7, 'I-地名': 8, 'B-政治的組織名': 9, 'I-政治的組織名': 10, 'B-施設名': 11, 'I-施設名': 12, 'B-法人名': 13, 'I-法人名': 14, 'B-製品名': 15, 'I-製品名': 16}} of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.

Map:   0%|          | 0/4274 [00:00<?, ? examples/s]

Map:   0%|          | 0/534 [00:00<?, ? examples/s]

#### モデルの準備

In [29]:
from transformers import (
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
)

# モデルを読み込む
model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    label2id=label2id,
    id2label=id2label
)

# パラメータをメモリ上に隣接した形で配置
# これを実行しない場合、モデルの保存でエラーになることがある
for param in model.parameters():
    param.data = param.data.contiguous()

# collate関数にDataCollatorForTokenClassificationを用いる
data_collator = DataCollatorForTokenClassification(tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/472 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

pytorch_model.bin:   0%|          | 0.00/447M [00:00<?, ?B/s]

Some weights of BertForTokenClassification were not initialized from the model checkpoint at cl-tohoku/bert-base-japanese-v3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [30]:
pprint(label2id)

{'B-その他の組織名': 1,
 'B-イベント名': 3,
 'B-人名': 5,
 'B-地名': 7,
 'B-政治的組織名': 9,
 'B-施設名': 11,
 'B-法人名': 13,
 'B-製品名': 15,
 'I-その他の組織名': 2,
 'I-イベント名': 4,
 'I-人名': 6,
 'I-地名': 8,
 'I-政治的組織名': 10,
 'I-施設名': 12,
 'I-法人名': 14,
 'I-製品名': 16,
 'O': 0}

In [ ]:
pprint(id2label)

{0: 'O',
 1: 'B-その他の組織名',
 2: 'I-その他の組織名',
 3: 'B-イベント名',
 4: 'I-イベント名',
 5: 'B-人名',
 6: 'I-人名',
 7: 'B-地名',
 8: 'I-地名',
 9: 'B-政治的組織名',
 10: 'I-政治的組織名',
 11: 'B-施設名',
 12: 'I-施設名',
 13: 'B-法人名',
 14: 'I-法人名',
 15: 'B-製品名',
 16: 'I-製品名'}

#### モデルのファインチューニング

In [32]:
from transformers import Trainer, TrainingArguments
from transformers.trainer_utils import set_seed

# 乱数シードを42に固定する
set_seed(42)

# Trainerに渡す引数を初期化する
training_args = TrainingArguments(
    output_dir="output_bert_ner", # 結果の保存フォルダ
    per_device_train_batch_size=32, # 訓練時のバッチサイズ
    per_device_eval_batch_size=32, # 評価時のバッチサイズ
    learning_rate=1e-4, # 学習率
    lr_scheduler_type="linear", # 学習率スケジューラ
    warmup_ratio=0.1, # 学習率のウォームアップ
    num_train_epochs=5, # 訓練エポック数
    evaluation_strategy="epoch", # 評価タイミング
    save_strategy="epoch", # チェックポイントの保存タイミング
    logging_strategy="epoch", # ロギングのタイミング
    fp16=True, # 自動混合精度演算の有効化
    report_to="none",  # 外部ツールへのログを無効化
)

# Trainerを初期化する
trainer = Trainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=validation_dataset,
    data_collator=data_collator,
    args=training_args,
)

# 訓練する
trainer.train()

TrainOutput(global_step=670, training_loss=0.15880151764670414, metrics={'train_runtime': 200.6938, 'train_samples_per_second': 106.481, 'train_steps_per_second': 3.338, 'total_flos': 1070012411245680.0, 'train_loss': 0.15880151764670414, 'epoch': 5.0})

In [33]:
pprint(train_dataset[0])

{'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 'input_ids': [2,
               16972,
               14284,
               384,
               50,
               13634,
               7075,
               20218,
               18124,
               7045,
               464,
               12913,
               385,
               3],
 'labels': [-100, 1, 2, 0, 1, 2, 2, 2, 2, 2, 0, 0, 0, -100],
 'special_tokens_mask': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

#### モデルの保存

##### Huging Face Hubへの保存

In [34]:
from huggingface_hub import login
from google.colab import userdata
from huggingface_hub import login
login(token=userdata.get("HF_TOKEN"))

login()

# Hugging Face Hubのリポジトリ名
repo_name = "tact-m/bert-base-japanese-v3-jnli"
# トークナイザとモデルをアップロード
tokenizer.push_to_hub(repo_name)
model.push_to_hub(repo_name)

TimeoutException: Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.

### 6.3.2 固有表現の予測・抽出

#### 固有表現ラベルの予測

In [35]:
def convert_list_dict_to_dict_list(
    list_dict: dict[str, list]
) -> list[dict[str, list]]:
    """ミニバッチのデータを事例単位のlistに変換"""
    dict_list = []
    # dictのキーのlistを作成
    keys = list(list_dict.keys())
    for idx in range(len(list_dict[keys[0]])):  # 各事例で処理する
        # dictの各キーからデータを取り出してlistに追加する
        dict_list.append({key: list_dict[key][idx] for key in keys})
    return dict_list

In [36]:
# ミニバッチのデータを事例単位のlistに変換する
list_dict = {
    "input_ids": [[0,1], [2,3]],
    "labels": [[1,2], [3,4]]
}
dict_list = convert_list_dict_to_dict_list(list_dict)
print(f"input: {list_dict}")
print(f"output: {dict_list}")

input: {'input_ids': [[0, 1], [2, 3]], 'labels': [[1, 2], [3, 4]]}
output: [{'input_ids': [0, 1], 'labels': [1, 2]}, {'input_ids': [2, 3], 'labels': [3, 4]}]

In [37]:
from tqdm import tqdm
from torch.utils.data import DataLoader
from transformers import PreTrainedModel

def run_prediction(
    dataloader: DataLoader,
    model: PreTrainedModel
) -> list[dict[str, Any]]:
    """予測スコアに基づき固有表現ラベルを予測"""
    predictions = []
    for batch in tqdm(dataloader):  # 各ミニバッチを処理する
        inputs = {
            k: v.to(model.device)
            for k, v in batch.items()
            if k != "special_tokens_mask"
        }
        # 予測スコアを取得する
        logits = model(**inputs).logits
        # 最もスコアの高いIDを取得する
        batch["pred_label_ids"] = logits.argmax(-1)
        batch = {k: v.cpu().tolist() for k, v in batch.items()}
        # ミニバッチのデータを事例単位のlistに変換する
        predictions += convert_list_dict_to_dict_list(batch)
    return predictions

In [38]:
# ミニバッチの作成にDataLoaderを用いる
validation_dataloader = DataLoader(
    validation_dataset,
    batch_size=32,
    shuffle=False,
    collate_fn=data_collator,
)
# 固有表現ラベルを予測する
predictions = run_prediction(validation_dataloader, model)
print(predictions[0]["pred_label_ids"])

100%|██████████| 17/17 [00:00<00:00, 17.75it/s]

[0, 0, 15, 16, 0, 0, 13, 14, 14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 13, 14, 14, 14, 13, 0, 0, 0, 0, 0, 15, 15, 15, 15, 13, 14, 14, 14, 16, 15, 13, 13, 14, 14, 0, 0, 0, 0, 13, 14, 14, 14, 13, 13, 13, 14, 14, 0, 15, 0, 0, 13, 0, 15, 15, 16, 0, 13, 14, 14, 14, 14, 13, 0, 0, 15, 15, 15, 16, 0, 13, 13, 14]

In [39]:
for pred_label_id in predictions[0]["pred_label_ids"]:
    print(id2label[pred_label_id])

O
O
B-製品名
I-製品名
O
O
B-法人名
I-法人名
I-法人名
O
O
O
O
O
O
O
O
O
B-製品名
B-法人名
I-法人名
I-法人名
I-法人名
B-法人名
O
O
O
O
O
B-製品名
B-製品名
B-製品名
B-製品名
B-法人名
I-法人名
I-法人名
I-法人名
I-製品名
B-製品名
B-法人名
B-法人名
I-法人名
I-法人名
O
O
O
O
B-法人名
I-法人名
I-法人名
I-法人名
B-法人名
B-法人名
B-法人名
I-法人名
I-法人名
O
B-製品名
O
O
B-法人名
O
B-製品名
B-製品名
I-製品名
O
B-法人名
I-法人名
I-法人名
I-法人名
I-法人名
B-法人名
O
O
B-製品名
B-製品名
B-製品名
I-製品名
O
B-法人名
B-法人名
I-法人名

#### 固有表現の抽出

In [40]:
from seqeval.metrics.sequence_labeling import get_entities

def extract_entities(
    predictions: list[dict[str, Any]],
    dataset: list[dict[str, Any]],
    tokenizer: PreTrainedTokenizer,
    id2label: dict[int, str]
) -> list[dict[str, Any]]:
    """固有表現を抽出"""
    results = []
    for prediction, data in zip(predictions, dataset):
        # 文字のlistを取得する
        characters = list(data["text"])

        # 特殊トークンを除いたトークンのlistと予測ラベルのlistを取得する
        tokens, pred_labels = [], []
        all_tokens = tokenizer.convert_ids_to_tokens(prediction["input_ids"])
        for token, label_id in zip(all_tokens, prediction["pred_label_ids"]):
            # 特殊トークン以外をlistに追加する
            if token not in tokenizer.all_special_tokens:
                tokens.append(token)
                pred_labels.append(id2label[label_id])
        
        # 文字のlistとトークンのlistのアライメントを取る
        _, token_to_char_indices = get_alignments(characters, tokens)
        
        # 予測ラベルのlistから固有表現タイプとトークン単位の開始位置と終了位置を取得して、
        # それらを正解データと同じ形式に変換する
        pred_entities = []
        for entity in get_entities(pred_labels):
            entity_type, token_start, token_end = entity
            # 文字単位の開始位置を取得する
            char_start = token_to_char_indices[token_start][0]
            # 文字単位の終了位置を取得する
            char_end = token_to_char_indices[token_end][-1] + 1
            pred_entity = {
                "name": "".join(characters[char_start:char_end]),
                "span": [char_start, char_end],
                "type": entity_type,
            }
            pred_entities.append(pred_entity)
        data["pred_entities"] = pred_entities
        results.append(data)
    return results

In [41]:
# 固有表現を抽出する
results = extract_entities(
    predictions, dataset["validation"], tokenizer, id2label
)
pprint(results[0:3])

[{'curid': '1662110',
  'entities': [{'name': '復活篇', 'span': [1, 4], 'type': '製品名'},
               {'name': 'グリーンバニー', 'span': [6, 13], 'type': '法人名'}],
  'pred_entities': [{'name': '復活篇', 'span': [1, 4], 'type': '製品名'},
                    {'name': 'グリーンバニー', 'span': [6, 13], 'type': '法人名'}],
  'text': '「復活篇」はグリーンバニーからの発売となっている。'},
 {'curid': '3024498',
  'entities': [{'name': '日刊ゲンダイ', 'span': [19, 25], 'type': '法人名'}],
  'pred_entities': [{'name': '日刊ゲンダイ', 'span': [19, 25], 'type': '法人名'}],
  'text': 'これらにより実質的な証拠調べが遅れたと日刊ゲンダイは報じている。'},
 {'curid': '3576262',
  'entities': [{'name': 'アンドリュー・スミス', 'span': [6, 16], 'type': '人名'}],
  'pred_entities': [{'name': 'アンドリュー・スミス', 'span': [6, 16], 'type': '人名'}],
  'text': 'プログラマのアンドリュー・スミスによれば、体の動きと頭の動きを独立させてしまうと、「カンニングできて」しまうパズルがあるという。'}]

### 6.3.3 検証セットを使用したモデルの選択

In [42]:
from glob import glob

best_score = 0
# 各チェックポイントで処理する
for checkpoint in sorted(glob("output_bert_ner/checkpoint-*")):
    # print(checkpoint)
    # モデルを読み込む
    model = AutoModelForTokenClassification.from_pretrained(
        checkpoint
    )
    model.to("cuda:0")
    # 固有表現ラベルを予測する
    predictions = run_prediction(validation_dataloader, model)
    # 固有表現ラベルを抽出する
    results = extract_entities(
        predictions,
        dataset["validation"],
        tokenizer,
        id2label
    )
    # 正解データと予測データのラベルのlistを作成する
    true_labels, pred_labels = convert_results_to_labels(results)
    # 評価スコアを算出する
    scores = compute_scores(true_labels, pred_labels, "micro")
    if best_score < scores["f1-score"]:
        best_score = scores["f1-score"]
        best_model = model

100%|██████████| 17/17 [00:03<00:00,  4.75it/s]
100%|██████████| 17/17 [00:03<00:00,  4.71it/s]
100%|██████████| 17/17 [00:03<00:00,  4.74it/s]
100%|██████████| 17/17 [00:03<00:00,  4.31it/s]
100%|██████████| 17/17 [00:03<00:00,  4.97it/s]

### 6.3.4 性能評価

In [43]:
# テストセットに対して前処理を行う
test_dataset = dataset["test"].map(
    preprocess_data,
    fn_kwargs = {
        "tokenizer": tokenizer,
        "label2id": label2id,
    },
    remove_columns =dataset["test"].column_names,
)
# ミニバッチの作成にDataLoaderを用いる
test_dataloader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False,
    collate_fn=data_collator,
)
# 固有表現ラベルを予測する
predictions = run_prediction(test_dataloader, best_model)
# 固有表現を抽出する
results = extract_entities(
    predictions,
    dataset["test"],
    tokenizer,
    id2label
)
# 正解データと予測データのラベルlistを作成する
true_labels, pred_labels = convert_results_to_labels(results)
# 評価結果を出力する
print(classification_report(true_labels, pred_labels))

Map:   0%|          | 0/535 [00:00<?, ? examples/s]

100%|██████████| 17/17 [00:03<00:00,  4.50it/s]

              precision    recall  f1-score   support

     その他の組織名       0.76      0.83      0.79       100
       イベント名       0.84      0.92      0.88        93
          人名       0.94      0.95      0.95       287
          地名       0.88      0.86      0.87       204
      政治的組織名       0.77      0.87      0.82       106
         施設名       0.82      0.85      0.83       137
         法人名       0.87      0.87      0.87       248
         製品名       0.78      0.83      0.80       158

   micro avg       0.85      0.88      0.87      1333
   macro avg       0.83      0.87      0.85      1333
weighted avg       0.85      0.88      0.87      1333

### 6.3.5 エラー分析

In [44]:
def find_error_results(
    results: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """エラー事例を発見"""
    error_results = []
    for idx, result in enumerate(results):  # 各事例を処理する
        result["idx"] = idx
        # 正解データと予測データが異なるならばlistに加える
        if result["entities"] != result["pred_entities"]:
            error_results.append(result)
    return error_results

def output_text_with_label(
    result: dict[str, Any],
    entity_column: str,
) -> str:
    """固有表現ラベル付きテキストを出力"""
    text_with_label = ""
    entity_count = 0
    for i, char in enumerate(result["text"]):  # 各文字を処理する
        # 出力に加えていない固有表現の有無を判定する
        if entity_count < len(result[entity_column]):
            entity = result[entity_column][entity_count]
            # 固有表現の先頭の処理を行う
            if i == entity["span"][0]:
                entity_type = entity["type"]
                text_with_label += f" [({entity_type})] "
            text_with_label += char
            # 固有表現の末尾の処理を行う
            if i == entity["span"][1] - 1:
                text_with_label += "] "
                entity_count += 1
        else:
            text_with_label += char
    return text_with_label

In [45]:
# エラー事例を発見する
error_results = find_error_results(results)
# 3件のエラー事例を出力する
for result in error_results[:5]:
    idx = result["idx"]
    true_text = output_text_with_label(result, "entities")
    pred_text = output_text_with_label(result, "pred_entities")
    print(f"事例{idx}の正解: {true_text}")
    print(f"事例{idx}の予測: {pred_text}")
    print()

事例11の正解: このため、本形式は [(法人名)] 江ノ島電鉄] では電動貨車2号車と呼称されているほか、電貨2と呼称される場合もある。
事例11の予測: このため、本形式は [(法人名)] 江ノ島電鉄] では電動貨車2号車と呼称されているほか、 [(製品名)] 電貨] 2と呼称される場合もある。

事例16の正解: 「 [(製品名)] 兵動・野爆のキャンピング王国] 」とのコラボレーション番組。
事例16の予測: 「 [(人名)] 兵動]  [(製品名)] ・]  [(人名)] 野爆]  [(製品名)] のキャンピング王国] 」とのコラボレーション番組。

事例18の正解:  [(法人名)] 常盤木学園] 時代の同級生に [(その他の組織名)] なでしこジャパン] の [(人名)] 熊谷紗希] がいる。
事例18の予測:  [(施設名)] 常盤木学園] 時代の同級生に [(その他の組織名)] なでしこジャパン] の [(人名)] 熊谷紗希] がいる。

事例19の正解: テレビで狼男映画の「 [(製品名)] 倫敦の人狼] 」を見た [(人名)] フィル・エヴァリー] は「ロンドンの狼男というタイトルで踊り騒げる曲を書いてみないか」と [(法人名)] ジヴォン] に持ちかけた。
事例19の予測: テレビで狼男映画の「 [(製品名)] 倫敦の人狼] 」を見た [(人名)] フィル・エヴァリー] は「 [(製品名)] ロンドンの狼男] というタイトルで踊り騒げる曲を書いてみないか」と [(人名)] ジヴォン] に持ちかけた。

事例27の正解:  [(政治的組織名)] 李承晩政権] 期から [(政治的組織名)] 朴正煕政権] 期の1970年前後まで、南側の [(地名)] 大韓民国] よりも北側の [(地名)] 朝鮮民主主義人民共和国] の方が経済的な体力では勝っていたのである。
事例27の予測:  [(人名)] 李承晩]  [(政治的組織名)] 政権] 期から [(人名)] 朴正煕] 政権期の1970年前後まで、南側の [(地名)] 大韓民国] よりも北側の [(地名)] 朝鮮民主主義人民共和国] の方が経済的な体力では勝っていたのである。